name: geoutils
channels:
  - conda-forge
  - defaults
dependencies:
  - graph-tool
  - jupyter
  - netcdf4
  - python[version='>=3.8']
  - pandas
  - ipython
  - xarray
  - numpy
  - tqdm
  - multiprocess
  - metpy
  - pip
  - scipy
  - joblib
  - cartopy  # =0.22.0
  - matplotlib  #=3.8.2
  - palettable
  - ipywidgets
  - scikit-learn
  - windspharm
  - statsmodels
  - seaborn

